export const EMOTION_LABEL_JP: Record<string, string> = {
  Hope: '希望',
  Healing: '癒し',
  Courage: '勇気',
  Compassion: '思いやり',
  Harmony: '調和',
  Loneliness: '孤独',
  Joy: '喜び',
  Adventure: '冒険心',
  Friendship: '友情',
  Determination: '決意',
  Wonder: '驚き',
  Melancholy: '郷愁',
  Gratitude: '感謝',
  Nurture: '育み',
  Community: 'つながり',
  Resolve: '覚悟',
  Anxiety: '不安',
  Skyward: '空への想い',
  Innovation: '新しさ',
  Homesick: 'ホームシック',
  Trust: '信頼',
  Companionship: '相棒',
  Empathy: '共感',
  Playfulness: '遊び心',
  Protection: '守りたい気持ち',
  Fear: '恐れ',
  Rebirth: '再生',
  Solidarity: '連帯',
  Memory: '記憶',
  Future: '未来',
  Doubt: '揺らぎ',
};

export const getEmotionLabelJp = (id: string) => EMOTION_LABEL_JP[id];
