name: Deploy Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: webgames
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: |
          npm --workspace site run build
          npm --workspace apps/space run build
          npm --workspace apps/flappy run build
          npm --workspace apps/suika run build
          npm --workspace apps/emotion run build
          npm --workspace apps/tetris run build || true
      - name: Bundle artifact
        run: |
          rm -rf _site
          mkdir -p _site _site/games
          if [ -d dist/site ]; then
            cp -r dist/site/. _site/
          elif [ -d site/dist/site ]; then
            echo "INFO: dist/site が存在しないため site/dist/site を使用します"
            cp -r site/dist/site/. _site/
          else
            echo "ERROR: dist/site is missing (site build failed?)"
            exit 1
          fi
          for app in space flappy suika emotion tetris; do
            if [ -d "dist/$app" ]; then
              mkdir -p "_site/games/$app"
              cp -r "dist/$app"/. "_site/games/$app"
            else
              echo "WARN: dist/$app is missing (check $app build)"
            fi
          done
          if [ ! -f _site/index.html ]; then
            echo "ERROR: _site/index.html が生成されていません"
            exit 1
          fi
      - uses: actions/upload-pages-artifact@v3
        with:
          # uses: ステップには working-directory が効かないためリポジトリ直下で解決する
          path: webgames/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
